# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.6

script:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt

  - flake8 .
  - black --check .
  - pytest -v
  - coverage xml -o coverage.xml

after_success:
  - codecov -t 187f34b5-f3d4-46ae-b5da-115076299002
